config/routes.rb
Rails.application.routes.draw do
  resources :formularios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/formulario.rb
class Formulario < ApplicationRecord
    mount_uploader :picture, ImagenUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/formularios_controller.rb
class FormulariosController < ApplicationController
  before_action :set_formulario, only: %i[ show edit update destroy ]

  # GET /formularios or /formularios.json
  def index
    @formularios = Formulario.all
  end

  # GET /formularios/1 or /formularios/1.json
  def show
  end

  # GET /formularios/new
  def new
    @formulario = Formulario.new
  end

  # GET /formularios/1/edit
  def edit
  end

  # POST /formularios or /formularios.json
  def create
    @formulario = Formulario.new(formulario_params)

    respond_to do |format|
      if @formulario.save
        format.html { redirect_to @formulario, notice: "Formulario was successfully created." }
        format.json { render :show, status: :created, location: @formulario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @formulario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formularios/1 or /formularios/1.json
  def update
    respond_to do |format|
      if @formulario.update(formulario_params)
        format.html { redirect_to @formulario, notice: "Formulario was successfully updated." }
        format.json { render :show, status: :ok, location: @formulario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @formulario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formularios/1 or /formularios/1.json
  def destroy
    @formulario.destroy
    respond_to do |format|
      format.html { redirect_to formularios_url, notice: "Formulario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formulario
      @formulario = Formulario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def formulario_params
      params.require(:formulario).permit(:nombre, :telefono, :mascota, :sexo, :descripcion, :fecha, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/formularios_helper.rb
module FormulariosHelper
end

app/views/formularios/_form.html.erb
<%= render 'layouts/header' %>

<%= form_with(model: formulario) do |form| %>
  <% if formulario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(formulario.errors.count, "error") %> prohibited this formulario from being saved:</h2>

      <ul>
        <% formulario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-8 mx-auto" style="padding-bottom: 200px;padding-top: 100px">
  <div class="card card-body">


  <%= form.label :nombre %>
  <%= form.text_field :nombre %>


<%= form.label :telefono %>
<%= form.text_field :telefono %>


<%= form.label :mascota %>
<%= form.text_field :mascota %>


<%= form.label :sexo %>
<%= form.text_field :sexo %>

<%= form.label :descripcion %>
<%= form.text_area :descripcion %>

<%= form.label :fecha %>
<%= form.date_select :fecha %>

<%= form.label :picture %>
<%= form.file_field :picture %>
<div class="actions">
<%= form.submit %>
</div>
  </div>
  </div>

 



<% end %>

app/views/formularios/edit.html.erb
<h1>Edita el formulario</h1>
<%= render 'form', formulario: @formulario %>

<%= link_to 'Show', @formulario %> |
<%= link_to 'Back', formularios_path %>

app/views/formularios/index.html.erb
<%= render 'layouts/header' %>
<p id="notice"><%= notice %></p>
<div class="col-md-12" style="padding-bottom: 200px;padding-top: 100px">
<h2>Formularios</h2>
<div class="col-md-12" style="padding-bottom: 200px;padding-top: 20px">
<table class="table table-bordered" style= "background: honeydew;">
  <thead style="background-color: #343a40!important;color: white;text-align: center">
    <tr>
      <th>Nombre</th>
      <th>Telefono</th>
      <th>Mascota</th>
      <th>Sexo</th>
      <th>Descripcion</th>
      <th>Fecha</th>
      <th>Imagen</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @formularios.each do |formulario| %>
      <tr>
        <td><%= formulario.nombre %></td>
        <td><%= formulario.telefono %></td>
        <td><%= formulario.mascota %></td>
        <td><%= formulario.sexo %></td>
        <td><%= formulario.descripcion %></td>
        <td><%= formulario.fecha %></td>
        <td><%= image_tag formulario.picture.thumb.url, class: 'figure-img img-fluid rounded'  %></td>
        <td><%= link_to 'Show', formulario %></td>
        <td><%= link_to 'Edit', edit_formulario_path(formulario) %></td>
        <td><%= link_to 'Destroy', formulario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<br>

<%= link_to 'New Formulario', new_formulario_path %>
<%= render 'layouts/footer' %>

app/views/formularios/inicio.html.erb
<%= render 'layouts/header' %>
<div class="container p-4">
    <div class = "card card-body" style= font-family:Verdana, Geneva, Tahoma, sans-serif ;>
        <h1 id='inicio'> Bienvenidos a Pet Save </h1>
        <h2 > Adopta tu mascota </h2>
    </div>  
        <div class="row"  style="padding-top: 60px " >
            <div class="col-md-4">
                <img src="https://estaticos.muyinteresante.es/media/cache/1140x_thumb/uploads/images/gallery/59c4f5655bafe82c692a7052/gato-marron_0.jpg" class="img-fluid">
                <img  src="https://www.ecestaticos.com/image/clipping/79776773aab795837282c7d4947abaf7/por-que-nos-parece-que-los-perros-sonrien-una-historia-de-30-000-anos.jpg" class="img-fluid" >
                <img  class="img-fluid" src="https://estaticos.muyinteresante.es/media/cache/1140x_thumb/uploads/images/gallery/59a697445bafe8f6f6b3d6dc/hamster-sirio_0.jpg" >
                <img  class="img-fluid" src="https://s3.amazonaws.com/arc-wordpress-client-uploads/infobae-wp/wp-content/uploads/2017/11/30152236/Perros-vs-Gatos2.jpg">
            </div>
            <div class="col-md-8">
            <div class = "card card-body" style= font-family:Cambria ; >
                <h1 style="padding-top: 30px"> ¿QUIENES SOMOS? </h1>
                <h4 style="padding-top: 20px"> Somos una organizacion en la cual nos encargamos
                    de darle hogar y cuidado a mascotas abandonadas
                    con el fin de que puedan volver encontrar un hogar.</h4>
                <h1 style="padding-top: 80px">  ¿Como inscribir una mascota abandonada?</h1>
                <h4 style="padding-top: 30px"> 1. Registrate o inicia sesion. </h4>
                <h4 style="padding-top: 15px"> 2. Accede a la parte "Formularios" que 
                se encuentra en la parte superior de la pagina. </h4>
                <h4 style="padding-top: 15px"> 3. Ingresa los datos de la mascota y envia el formulario </h4>
                <h4 style="padding-top: 15px"> 4. Una vez ingresada la informacion recibiremos tus datos
                y nos pondremos en contacto para acoger la mascota. </h4>
                <h1 style="padding-top: 80px">  ¿Como adoptar una mascota?</h1>
                <h4 style="padding-top: 30px">  Sin necesidad de iniciar sesion puedes revisar 
                las mascotas disponibles en la parte superior de la pagina en "Mascotas"</h4>
            </div>
            </div>    
        </div>
    </div>
</div>
<%= render 'layouts/footer' %>

app/views/formularios/new.html.erb
<h1>New Formulario</h1>

<%= render 'form', formulario: @formulario %>

<%= link_to 'Back', formularios_path %>

app/views/formularios/show.html.erb
<%= render 'layouts/header' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @formulario.nombre %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @formulario.telefono %>
</p>

<p>
  <strong>Mascota:</strong>
  <%= @formulario.mascota %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @formulario.sexo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @formulario.descripcion %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @formulario.fecha %>
</p>

<p>
  <strong>Imagen:</strong>
  <%= image_tag @formulario.picture.thumb.url, class: 'figure-img img-fluid rounded' %>
</p>

<%= link_to 'Edit', edit_formulario_path(@formulario) %> |
<%= link_to 'Back', formularios_path %>

<%= render 'layouts/footer' %>

app/views/layouts/_footer.html.erb
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>

<!--<script src="./include/script.js"></script>-->
</body>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />

<footer id="dk-footer" class="dk-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-lg-4">
                    <div class="dk-footer-box-info">
                        <a href="index.html" class="footer-logo">
                            <img src="<%= asset_path 'lp.png' %>" alt="footer_logo" class="img-fluid">
                        </a>
                        <p class="footer-info-text">
                           Página de ONG para administrar animales en adopción.
                        </p>
                        <div class="footer-social-link">
                            <h3>Síguenos</h3>
                            <ul id="listasocial">
                                <li id="listasocial">
                                    <a href="#">
                                        <i class="fa fa-facebook"></i>
                                    </a>
                                </li>
                                <li id="listasocial">
                                    <a href="#">
                                        <i class="fa fa-twitter"></i>
                                    </a>
                                </li>
                                <li id="listasocial">
                                    <a href="#">
                                        <i class="fa fa-google-plus"></i>
                                    </a>
                                </li>
                                <li id="listasocial">
                                    <a href="#">
                                        <i class="fa fa-linkedin"></i>
                                    </a>
                                </li>
                                <li id="listasocial">
                                    <a href="#">
                                        <i class="fa fa-instagram"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <!-- End Social link -->
                    </div>
                    <!-- End Footer info 
                    <div class="footer-awarad">
                        <img src="" alt="">
                        <p>ONG 2021</p>
                    </div>-->
                </div>
                <!-- End Col -->
                <div class="col-md-12 col-lg-8">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="contact-us">
                                <div class="contact-icon">
                                    <i class="fa fa-map-o" aria-hidden="true"></i>
                                </div>
                                <!-- End contact Icon -->
                                <div class="contact-info">
                                    <h3>Guayaquil</h3>
                                    <p>Bosque Protector</p>
                                </div>
                                <!-- End Contact Info -->
                            </div>
                            <!-- End Contact Us -->
                        </div>
                        <!-- End Col -->
                        <div class="col-md-6">
                            <div class="contact-us contact-us-last">
                                <div class="contact-icon">
                                    <i class="fa fa-volume-control-phone" aria-hidden="true"></i>
                                </div>
                                <!-- End contact Icon -->
                                <div class="contact-info">
                                    <h3>099 999 9999</h3>
                                    <p>Llámanos</p>
                                </div>
                                <!-- End Contact Info -->
                            </div>
                            <!-- End Contact Us -->
                        </div>
                        <!-- End Col -->
                    </div>
                    <!-- End Contact Row -->
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="footer-widget footer-left-widget">
                                <div class="section-heading">
                                    <h3>Link de interés</h3>
                                    <span class="animate-border border-black"></span>
                                </div>
                                <ul>
                                    <li>
                                        <a href="#">About us</a>
                                    </li>
                                    <li>
                                        <a href="#">Services</a>
                                    </li>
                                    <li>
                                        <a href="#">Projects</a>
                                    </li>
                                    <li>
                                        <a href="#">Our Team</a>
                                    </li>
                                </ul>
                                <ul>
                                    <li>
                                        <a href="#">Contact us</a>
                                    </li>
                                    <li>
                                        <a href="#">Blog</a>
                                    </li>
                                    <li>
                                        <a href="#">Testimonials</a>
                                    </li>
                                    <li>
                                        <a href="#">Faq</a>
                                    </li>
                                </ul>
                            </div>
                            <!-- End Footer Widget -->
                        </div>
                        <!-- End col -->
                        <div class="col-md-12 col-lg-6">
                            <div class="footer-widget">
                                <div class="section-heading">
                                    <h3>Suscríbete</h3>
                                    <span class="animate-border border-black"></span>
                                </div>
                                <p id="textofooter"><!-- Don’t miss to subscribe to our new feeds, kindly fill the form below. -->
                                Mantenerte informado constantemente sobre nuestras actividades.</p>
                                <form action="#">
                                    <div class="form-row">
                                        <div class="col dk-footer-form">
                                            <input type="email" class="form-control" placeholder="Email Address">
                                            <button type="submit">
                                                <i class="fa fa-send"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                                <!-- End form -->
                            </div>
                            <!-- End footer widget -->
                        </div>
                        <!-- End Col -->
                    </div>
                    <!-- End Row -->
                </div>
                <!-- End Col -->
            </div>
            <!-- End Widget Row -->
        </div>
        <!-- End Contact Container -->


        <div class="copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <span>Copyright © 2021, All Right Reserved</span>
                    </div>
                    <!-- End Col -->
                    <div class="col-md-6">
                        <div class="copyright-menu">
                            <ul>
                                <li>
                                    <a href="#">Home</a>
                                </li>
                                <li>
                                    <a href="#">Terms</a>
                                </li>
                                <li>
                                    <a href="#">Privacy Policy</a>
                                </li>
                                <li>
                                    <a href="#">Contact</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- End col -->
                </div>
                <!-- End Row -->
            </div>
            <!-- End Copyright Container -->
        </div>
        <!-- End Copyright -->
        <!-- Back to top -->
        <div id="back-to-top" class="back-to-top">
            <button class="btn btn-dark" title="Back to Top" style="display: block;">
                <i class="fa fa-angle-up"></i>
            </button>
        </div>
        <!-- End Back to top -->
</footer>


</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pet Save</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<!--<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>-->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <%= favicon_link_tag 'favicon.ico' %>
</head>
<body style="background: url('<%= asset_path 'fondo.jfif' %>');" >
<nav class="navbar navbar-dark bg-dark">
    <div class="container">
        <a href="index.php" class="navbar-brand">Pet Save</a>
        <ul id="lista">
        <%= link_to 'home', @formulario %>
         
</ul>
    </div>
</nav>

app/views/layouts/_home.html.erb
<%= render 'layouts/header' %>
<div class="container p-4">
    <div class = "card card-body" style= font-family:Verdana, Geneva, Tahoma, sans-serif ;>
        <h1 id='inicio'> Bienvenidos a Pet Save </h1>
        <h2 > Adopta tu mascota </h2>
    </div>  
        <div class="row"  style="padding-top: 60px " >
            <div class="col-md-4">
                <img src="https://estaticos.muyinteresante.es/media/cache/1140x_thumb/uploads/images/gallery/59c4f5655bafe82c692a7052/gato-marron_0.jpg" class="img-fluid">
                <img  src="https://www.ecestaticos.com/image/clipping/79776773aab795837282c7d4947abaf7/por-que-nos-parece-que-los-perros-sonrien-una-historia-de-30-000-anos.jpg" class="img-fluid" >
                <img  class="img-fluid" src="https://estaticos.muyinteresante.es/media/cache/1140x_thumb/uploads/images/gallery/59a697445bafe8f6f6b3d6dc/hamster-sirio_0.jpg" >
                <img  class="img-fluid" src="https://s3.amazonaws.com/arc-wordpress-client-uploads/infobae-wp/wp-content/uploads/2017/11/30152236/Perros-vs-Gatos2.jpg">
            </div>
            <div class="col-md-8">
            <div class = "card card-body" style= font-family:Cambria ; >
                <h1 style="padding-top: 30px"> ¿QUIENES SOMOS? </h1>
                <h4 style="padding-top: 20px"> Somos una organizacion en la cual nos encargamos
                    de darle hogar y cuidado a mascotas abandonadas
                    con el fin de que puedan volver encontrar un hogar.</h4>
                <h1 style="padding-top: 80px">  ¿Como inscribir una mascota abandonada?</h1>
                <h4 style="padding-top: 30px"> 1. Registrate o inicia sesion. </h4>
                <h4 style="padding-top: 15px"> 2. Accede a la parte "Formularios" que 
                se encuentra en la parte superior de la pagina. </h4>
                <h4 style="padding-top: 15px"> 3. Ingresa los datos de la mascota y envia el formulario </h4>
                <h4 style="padding-top: 15px"> 4. Una vez ingresada la informacion recibiremos tus datos
                y nos pondremos en contacto para acoger la mascota. </h4>
                <h1 style="padding-top: 80px">  ¿Como adoptar una mascota?</h1>
                <h4 style="padding-top: 30px">  Sin necesidad de iniciar sesion puedes revisar 
                las mascotas disponibles en la parte superior de la pagina en "Mascotas"</h4>
            </div>
            </div>    
        </div>
    </div>
</div>

<%= render 'layouts/footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pet Save</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
     %> 
  </head>

  <body>
    <%= yield %>
  </body>
</html>